import type { NextPage } from "next";
import Head from "next/head";
import WalletConnect from "../components/WalletConnect";
import Link from "next/link";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setLoaded(true);
  }, []);

  return !loaded ? (
    <></>
  ) : (
    <div className="px-10">
      <Head>
        <title>Cardano DApp QuickStart</title>
        <meta
          name="description"
          content="Smart Contract scripts generated by Aiken"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="navbar bg-base-100">
        <div className="flex-1">
          <Link href="/" className="btn btn-ghost normal-case text-xl">
            Cardano
          </Link>
        </div>
        <div className="flex-none">
          <WalletConnect />
        </div>
      </div>

      <div className="mx-40 my-10">
        <Link href="/helios">
          <button className="btn btn-primary m-5">
            Smart Contract Examples
          </button>
        </Link>
      </div>
    </div>
  );
};

export default Home;
